apiVersion: v1
kind: Service
metadata:
  name: goalrev-ganache
  labels:
    app.kubernetes.io/app: goalrev-ganache
spec:
  selector:
    app.kubernetes.io/app: goalrev-ganache
  ports:
  - name: http
    protocol: TCP
    port: 8545
    targetPort: 8545
