apiVersion: apps/v1
kind: Deployment
metadata:
  name: goalrev-processor
  labels:
    app.kubernetes.io/app: goalrev-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: goalrev-processor
  template:
    metadata:
      labels:
        app.kubernetes.io/app: goalrev-processor
    spec:
      containers:
      - name: goalrev-processor
        image: freeverseio/goalrev-processor:{{ .Values.imageTag }}
        volumeMounts:
        - name: db-certificate
          mountPath: "/app/data"
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        imagePullPolicy: Always
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: goalrev-private-config
                key: postgresPassword
          - name: GRAPHQL_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: goalrev-private-config
                key: graphqlAccessToken
          - name: DB_HOST
            value: {{ .Values.postgresHost }}
          - name: DB_PORT
            value: {{ .Values.postgresPort | quote }}
          - name: DB_USER
            value: {{ .Values.postgresUser }}
          - name: DB_NAME
            value: {{ .Values.postgresDb }}
          - name: CORE_API_URL
            value: {{ .Values.apiInternalUrl }}
          - name: APP_PORT
            value: {{ .Values.processorPort | quote }}
          - name: SSL_CA_CERT
            value: "./data/ca-certificate.pem"
          - name: PLAY_MATCHES_SCHEDULER
            value: {{ .Values.playMatchesScheduler | quote }}
          - name: GRAPHQL_ENDPOINT
            value: {{ .Values.graphqlEndpoint }}
          - name: CHAIN_ID
            value: {{ .Values.chainId | quote }}
          - name: CONTRACT_ADDRESS
            value: {{ .Values.contractAddress | quote }}

        ports:
        - containerPort: {{ .Values.processorPort }}
      volumes:
      - name: db-certificate
        secret:
          secretName: db-cert
        
      imagePullSecrets:
      - name: docker-secret
