apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goalrev-processor-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: '1'
    nginx.ingress.kubernetes.io/auth-tls-error-page: 'http://www.mysite.com/error-cert.html'
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-freeverse
    nginx.ingress.kubernetes.io/client-max-body-size: 6M
    nginx.ingress.kubernetes.io/proxy-body-size: 6M
spec:
  tls:
    - hosts:
        - {{ .Values.processorHost }}
      secretName: goalrev-processor-tls
  rules:
    - host: {{ .Values.processorHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goalrev-processor
                port:
                  number: 3000
