apiVersion: v1
kind: Service
metadata:
  name: goalrev-processor
  labels:
    app.kubernetes.io/app: goalrev-processor
spec:
  selector:
    app.kubernetes.io/app: goalrev-processor
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.processorPort }}
    targetPort: {{ .Values.processorPort }}
