releases:
  - name: goalrev-api-release
      namespace: "{{ .Values.namespace }}"
      installed: true
      createNamespace: false
      chart: .
      values:
        - imageTag: {{ .Values.imageTag }}
        - postgresUser: {{ .Values.postgresUser }}
        - postgresHost: {{ .Values.postgresHost }}
        - postgresDb: {{ .Values.postgresDb }}
        - postgresPort: {{ .Values.postgresPort }}
        - apiHost: {{ .Values.apiHost }}
