 const PLAYERS_PER_TEAM_MAX = 25;
 const PLAYERS_PER_TEAM_MIN = 11;
 const NO_SUBSTITUTES = 11;
 const NO_LINEUP = PLAYERS_PER_TEAM_MAX; 
 const VERSES_PER_ROUND = 672; // 96 * 7days
 const NULL_TIMEZONE = 0;
 const VERSES_PER_DAY = 96;
 const SECS_BETWEEN_VERSES = 900; // 15 mins
 const MATCHDAYS_PER_ROUND = 14;
 const DAYS_PER_ROUND = 7;
 const DEFAULT_ENCODED_TACTIC = "340596594427581673436941882753025";

export {
    PLAYERS_PER_TEAM_MAX,
    PLAYERS_PER_TEAM_MIN,
    NO_SUBSTITUTES,
    NO_LINEUP,
    VERSES_PER_ROUND,
    NULL_TIMEZONE,
    VERSES_PER_DAY,
    SECS_BETWEEN_VERSES,
    MATCHDAYS_PER_ROUND,
    DAYS_PER_ROUND,
    DEFAULT_ENCODED_TACTIC
}