repositories:
  - name: stable
    url: https://charts.helm.sh/stable

  - name: jetstack
    url: https://charts.jetstack.io

environments:
  default:
    values:
      - ./environments/dev/values.yaml
  development:
    values:
      - ./environments/dev/values.yaml
  staging:
    values:
      - ./environments/staging/values.yaml
  production:
    values:
      - ./environments/production/values.yaml

helmfiles:
  - path: "charts/goalrev-api/helmfile.yaml"
    values:
      - namespace: {{ .Values.namespace }}
      - imageTag: {{ requiredEnv "CIRCLE_SHA1" }}
      - postgresUser: {{ .Values.postgresUser }}
      - postgresHost: {{ .Values.postgresHost }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresPort: {{ .Values.postgresPort | quote }}
      - apiHost: {{ .Values.apiHost }}
  - path: "charts/goalrev-processor/helmfile.yaml"
    values:
      - namespace: {{ .Values.namespace }}
      - imageTag: {{ requiredEnv "CIRCLE_SHA1" }}
      - postgresUser: {{ .Values.postgresUser }}
      - postgresHost: {{ .Values.postgresHost }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresPort: {{ .Values.postgresPort | quote }}
      - processorHost: {{ .Values.processorHost }}
      - processorPort: {{ .Values.processorPort | quote }}
      - apiInternalUrl: {{ .Values.apiInternalUrl }}
      - graphqlEndpoint: {{ .Values.graphqlEndpoint }}
      - chainId: {{ .Values.chainId }}
      - contractAddress: {{ .Values.contractAddress }}
      - playMatchesScheduler: {{ .Values.playMatchesScheduler | quote }}
      - transferScheduler: {{ .Values.transferScheduler | quote }}
      - mintPendingTeamsScheduler: {{ .Values.mintPendingTeamsScheduler | quote }}
      - broadcastPlayersPendingScheduler: {{ .Values.broadcastPlayersPendingScheduler | quote }}
      - blockMargin: {{ .Values.blockMargin | quote }}
      - defaultTeamId: {{ .Values.defaultTeamId }}
      - pendingTeamsLimit: {{ .Values.pendingTeamsLimit | quote }}
      - broadcastBatchSizeOnChain: {{ .Values.broadcastBatchSizeOnChain | quote  }}
      - broadcastBatchSizeDb: {{ .Values.broadcastBatchSizeDb | quote  }}
      - evolveBatchSizeOnChain: {{ .Values.evolveBatchSizeOnChain | quote  }}
      - evolveBatchSizeDb: {{ .Values.evolveBatchSizeDb | quote  }}
      - numDaysToSetTeamsToZombies: {{ .Values.numDaysToSetTeamsToZombies | quote  }}
  - path: "charts/goalrev-core/helmfile.yaml"
    values:
      - namespace: {{ .Values.namespace }}
      - imageTag: {{ requiredEnv "CIRCLE_SHA1" }}
      - coreAppPort: {{ .Values.coreAppPort }}
      - ganacheRpcUrl: {{ .Values.ganacheRpcUrl }}
      - ganacheContractLeagues: {{ .Values.ganacheContractLeagues }}    
      - ganacheContractPlayAndEvolve: {{ .Values.ganacheContractPlayAndEvolve }}
      - ganacheContractUtils: {{ .Values.ganacheContractUtils }}
  - path: "charts/goalrev-ganache/helmfile.yaml"
    values:
      - namespace: {{ .Values.namespace }}
      - imageTag: {{ requiredEnv "CIRCLE_SHA1" }}
