repositories:
  - name: stable
    url: https://charts.helm.sh/stable

  - name: jetstack
    url: https://charts.jetstack.io

environments:
  default:
    values:
      - ./environments/dev/values.yaml
  development:
    values:
      - ./environments/dev/values.yaml
  staging:
    values:
      - ./environments/staging/values.yaml
  production:
    values:
      - ./environments/production/values.yaml

helmfiles:
  - path: "charts/goalrev-api/helmfile.yaml"
    values:
      - namespace : {{ .Values.namespace }}
      - imageTag: {{ requiredEnv "CIRCLE_SHA1" }}
      - postgresUser: {{ .Values.postgresUser }}
      - postgresHost: {{ .Values.postgresHost }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresPort: {{ .Values.postgresPort }} 
      - apiHost: {{ .Values.apiHost }}