apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketplace-redirect
  namespace: protostar
  annotations:
    kubernetes.io/ingress.class: nginx        
    cert-manager.io/cluster-issuer: letsencrypt-freeverse
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on" 
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"                                                                                                                                         
spec:
  tls:
    - hosts:
        - marketplace.goalrev.com
      secretName: marketplace-redirect-cert
  rules:
    - host: marketplace.goalrev.com
