apiVersion: v1
kind: Service
metadata:
  name: goalrev-api
  labels:
    app.kubernetes.io/app: goalrev-api
spec:
  selector:
    app.kubernetes.io/app: goalrev-api
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
