apiVersion: v1
kind: Service
metadata:
  name: goalrev-core
  labels:
    app.kubernetes.io/app: goalrev-core
spec:
  selector:
    app.kubernetes.io/app: goalrev-core
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.coreAppPort }}
    targetPort: {{ .Values.coreAppPort }}
