namespace: goalrev
apiHost: goalrevapi.gorengine.com
apiInternalUrl: http://goalrev-core.goalrev.svc.cluster.local:3001
postgresHost: db-postgresql-ams3-02994-do-user-14140340-0.j.db.ondigitalocean.com
postgresDb: defaultdb
postgresPort: "25060"
postgresUser: "doadmin"
processorHost: goalrev-processor.gorengine.com
processorPort: "3000"
coreAppPort: "3001"
ganacheRpcUrl: http://goalrev-ganache.goalrev.svc.cluster.local:8545/
ganacheContractLeagues: "0x630589690929E9cdEFDeF0734717a9eF3Ec7Fcfe"
ganacheContractPlayAndEvolve: "0x6eD79Aa1c71FD7BdBC515EfdA3Bd4e26394435cC"
ganacheContractUtils: "0xA94B7f0465E98609391C623d0560C5720a3f2D33"
playMatchesScheduler: "*/10 * * * * *"
mintPendingTeamsScheduler: "*/30 * * * * *"
transferScheduler: "*/50 * * * * *"
graphqlEndpoint: https://api.laosnetwork.io/graphql
chainId: "137"
contractAddress: "0x7404a72f74eed1c9808f6d371bdb2faac362df1d"
blockMargin: "10"
defaultTeamId: "999"
