releases:
  - name: goalrev-truffle-core-release
    namespace: "{{ .Values.namespace }}"  # Correct indentation here
    installed: true
    createNamespace: false
    chart: .
    values:
      - imageTag: {{ .Values.imageTag }}
      - apiHost: {{ .Values.apiHost }}
